### ISSUE TITLE
ecs.security_group.wordpress cannot have allow all egress

### ISSUE THREAD

**Issue by roperto** [devopsacademyau/2020-jun-project1-externals#31]
**Explanation**

If the wordpress got hacked, it could upload information to another server or be used as an attack vector to other places.

At fist we are not allowing any outgoing connection from the WordPress, we may revisit that decision later.

**Tasks**

In `modules/ecs/main.tf`remove the "egress" from the security group.

**Comment by raghunadhpokkalath** [comment]
closing this is as this is not required any more
