### ISSUE TITLE
Wordpress - ECS Task and Service

### ISSUE THREAD

**Issue by caiocezart** [devopsacademyau/2020-jun-project1-externals#9]
**Objectives:**
- Task:
	- Uses custom image in ECR from #07
	- Uses EFS created #3
	- Consumes parameters from SSM created in #05
	- Memory is set to 128
	- Any required IAM role is associated with the task
- Service:
	- Uses the task defined above
	- Service type is replica
	- Deployment type is configured for rolling update or blue/green
	- Should have two tasks running at the same time

**Acceptance Criteria:**
- Task is running succesfully(healthy state) in the cluster
- Port being exposed at the host is random

**Comment by carloshz4** [comment]
Hi @caiocezart, just double checking with you, the links above referring to other issues are incorrect?  

Say for instance:
"Uses custom image in ECR from #7".     But #7 is the RDS Aurora Database.  

It seems the sentences are correct but the reference and link to the issues are incorrect?

**Comment by raghunadhpokkalath** [comment]
Completed the changed and merged to Master. Used public subnets as private subnets are having some issues when used with fargate cluster. Raised #49 to look into the private subnet issue
